### ISSUE TITLE
Goals I'd Like To Hit For A Summer Restart

### ISSUE THREAD

**Issue by minin43** [minin43/ConquestTDM#66]
- [x] Cleanup of timed events (happy hour, 2x exp weekends)
- [x] Finalize rewrite of shop (Includes setting up backend info for weapon skins & player models)
- [x] Rewrite loadout menu (Fixes for #21 #20 #18)
- [x] Fix #48 
- [x] Implement admin commands for #64 
- [x] Implement spectator bug fixes #56 
- [x] Auto-give players their melee weapon #50 
- [x] Fix #45 
- [x] Fix #53 
- [x] Fix mapvote key text
- [x] "Reset" player weapon progress (remove weapon buys & attachment progress, but keep prestige tokens, cash, and player level)
- [x] Re-do Help menu with new menus & explanations
- [x] Finish VIP backend
